### PR TITLE
[OBST-268] use latest SSO submodule with tests

### PR DESCRIPTION
**Pull request by Ladicek**

### CODE REVIEW

**Comment by Ladicek** [comment]
Please hold, I need to do one fix in the SSO submodule first.

EDIT: will update this PR once https://github.com/obsidian-toaster-quickstarts/redhat-sso/pull/5 is merged.

**Comment by Ladicek** [comment]
This is now ready to merge.

**Comment by Ladicek** [comment]
Bump?

**Comment by heiko-braun** [comment]
@Ladicek maybe we wait for the rhoar ci to turn green first?

**Comment by Ladicek** [comment]
@heiko-braun It only runs post-merge.

**Comment by Ladicek** [comment]
Ah, you mean the JAX-RS Client issue. Right, we can wait for that to be fixed.

**Review by kenfinnigan — APPROVED** [review]

**Comment by Ladicek** [comment]
Thanks!

**Pull request merged**
