### PR TITLE
Workaround integrations test setup failures. 

### PR DESCRIPTION
**Pull request by heiko-braun**
Needs to be investigated in the future

### CODE REVIEW

**Comment by heiko-braun** [comment]
@Ladicek this is the workaround we talked about yesterday

**Comment by Ladicek** [comment]
Do you wanna remove the `RestAssured.useRelaxedHTTPSValidation()` bit? I added it only because of the SSO server.

Otherwise LGTM.

**Comment by heiko-braun** [comment]
@Ladicek done

**Review by Ladicek — APPROVED** [review]

**Comment by Ladicek** [comment]
Thanks @heiko-braun!

**Pull request merged**
